title: Введение в математические пакеты
description: Тут размещены материалы второго модуля курса “Введение в математические пакеты” для студентов первого курса кафедры ФН-1 МГТУ им. Н.Э. Баумана.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
